int o1;
int o2;
int o3;
int o4;
PFont font;
float d = dist (mouseX, mouseY, 215, 390);
float x, y, tam;
PImage imagenuno, imagendos;
PImage [] images = new PImage [6];
//String [] filenames =  ("verde.png","naranja.png","azul.png","rojo.png","violeta.png","amarillo.png");
String estado = "estado1";
