int posXob1;
int posYob1;
int posXob2;
int posYob2;
int posXob3;
int posYob3;
int obancho;
int obalto;
int max = 7;
float posY = 30;
float posX =100;
PFont font;
float w,h;
float vel;
float x, y;
PImage imagenuno, imagendos, boton1,ruta, ob1, ob2, ob3 ;
PImage [] images = new PImage [max];
String [] filenames;
String estado = "estado1";
