int posXob1;
int posYob1;
int posXob2;
int posYob2;
int posXob3;
int posYob3;
int obancho;
int obalto;
int max = 4;
float posY = 30;
float posX =100;
PFont font;
float w,h,w2,h2,w3,h3;
float vel;
float x, y,x2,y2,x3,y3;
PImage imagenuno, imagendos, boton1,ruta, ob1, ob2, ob3,boton2 ;
PImage [] images = new PImage [max];
String [] filenames;
String estado = "estado1";
